/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Medicine = IDL.Record({
  'name' : IDL.Text,
  'dosageNotes' : IDL.Text,
});
export const Disease = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'medicines' : IDL.Vec(Medicine),
});

export const idlService = IDL.Service({
  'getAllDiseases' : IDL.Func([], [IDL.Vec(Disease)], ['query']),
  'getDisease' : IDL.Func([IDL.Text], [Disease], ['query']),
  'initialize' : IDL.Func([], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Medicine = IDL.Record({ 'name' : IDL.Text, 'dosageNotes' : IDL.Text });
  const Disease = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'medicines' : IDL.Vec(Medicine),
  });
  
  return IDL.Service({
    'getAllDiseases' : IDL.Func([], [IDL.Vec(Disease)], ['query']),
    'getDisease' : IDL.Func([IDL.Text], [Disease], ['query']),
    'initialize' : IDL.Func([], [], []),
  });
};

export const init = ({ IDL }) => { return []; };